[package]
name = "proof-forge-output-solidity"
version.workspace = true
edition.workspace = true

[dependencies]
proof-forge-core = { workspace = true }

anyhow = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
