[package]
name = "proof-forge-input-snarkjs"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

alloy-primitives = { workspace = true }

proof-forge-core = { workspace = true }
