[package]
name = "proof-forge-core"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["serde"] }
anyhow = { workspace = true }

serde = { workspace = true }
